FROM ://microsoft.com

# Install CMake and build essentials
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends build-essential cmake ninja-build git
